server:
  port: 8081

spring:
  application:
    name: pet_studio_spring
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pet
    username: bootuser
    password: bootuser