server:
  port: 8081

spring:
  application:
    name: pet_studio_spring

  file:
    boardImagePath: C:/Temp/boardImageUpload/
    profileImagePath: C:/Temp/profileImageUpload/

  profiles:
    active: local
    include: common, secret